/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FileAccessControl } from "./FileAccessControl";
export type { FileAccessControl0 } from "./FileAccessControl0";
